### ISSUE TITLE
Panic when `inlet.snmp.communities` is a string.

### ISSUE THREAD

**Issue by vincentbernat** [vincentbernat/akvorado#115]
Hello!

Akvorado version: 1.5.6 / 1.5.7
Docker installation

After starting a new installation i get an error `panic: reflect: call of reflect.Value.MapIndex on string Value`

<details>
  <summary>logs from orchestrator</summary>
  

```
~ ➤ docker logs -f akvorado-akvorado-orchestrator-1
goroutine 1 [running]:
reflect.flag.mustBe(...)
	/usr/local/go/src/reflect/value.go:221
reflect.Value.MapIndex({0x14dc7c0?, 0xc000415190?, 0x1700068?}, {0x14dc7c0, 0x1f17e10, 0x98})
	/usr/local/go/src/reflect/value.go:1650 +0x22d
akvorado/inlet/snmp.ConfigurationUnmarshallerHook.func1({0x153fdc0?, 0xc00040dc20?, 0x1f46d98?}, {0x167d7a0?, 0xc00019d898?, 0xc0007695c8?})
	/app/inlet/snmp/config.go:110 +0x5ef
github.com/mitchellh/mapstructure.DecodeHookExec({0x1537660?, 0x1d16ac8?}, {0x153fdc0?, 0xc00040dc20?, 0x2?}, {0x167d7a0?, 0xc00019d898?, 0x15682a0?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/decode_hooks.go:51 +0x144
github.com/mitchellh/mapstructure.ComposeDecodeHookFunc.func1({0x153fdc0?, 0xc00040dc20?, 0x1f46d98?}, {0x167d7a0?, 0xc00019d898?, 0xc000769710?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/decode_hooks.go:69 +0x10c
github.com/mitchellh/mapstructure.DecodeHookExec({0x1537660?, 0xc0003b07a0?}, {0x153fdc0?, 0xc00040dc20?, 0x2?}, {0x167d7a0?, 0xc00019d898?, 0x15682a0?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/decode_hooks.go:51 +0x144
github.com/mitchellh/mapstructure.ComposeDecodeHookFunc.func1({0x153fdc0?, 0xc00040dc20?, 0x45eff7?}, {0x167d7a0?, 0xc00019d898?, 0x0?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/decode_hooks.go:69 +0x10c
github.com/mitchellh/mapstructure.DecodeHookExec({0x1537660?, 0xc0003b07c0?}, {0x153fdc0?, 0xc00040dc20?, 0x4?}, {0x167d7a0?, 0xc00019d898?, 0xc000711339?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/decode_hooks.go:51 +0x144
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc000014b60, {0xc000711330, 0xd}, {0x153fdc0?, 0xc00040dc20?}, {0x167d7a0?, 0xc00019d898?, 0x0?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:459 +0x179
github.com/mitchellh/mapstructure.(*Decoder).decodeStructFromMap(0xc000014b60, {0xc0007110e0, 0x8}, {0x153fdc0?, 0xc00040db30?, 0x5?}, {0x165ee40?, 0xc00019d860?, 0x15?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:1411 +0x1bd0
github.com/mitchellh/mapstructure.(*Decoder).decodeStruct(0x1537660?, {0xc0007110e0, 0x8}, {0x153fdc0?, 0xc00040db30?}, {0x165ee40?, 0xc00019d860?, 0x4180c6?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:1235 +0x5b4
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc000014b60, {0xc0007110e0, 0x8}, {0x153fdc0?, 0xc00040db30?}, {0x165ee40?, 0xc00019d860?, 0x1f17a50?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:482 +0x309
github.com/mitchellh/mapstructure.(*Decoder).decodeSlice(0xc000014b60, {0x1424af5, 0x5}, {0x14c2cc0, 0xc000118468?}, {0x14ba600?, 0xc00015ddb0?, 0xc00015ddb0?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:1139 +0x9f4
github.com/mitchellh/mapstructure.(*Decoder).decodeSlice(0xc000014b60, {0x1424af5, 0x5}, {0x153fdc0, 0xc00040db30?}, {0x14ba600?, 0xc00015ddb0?, 0xc0003815a8?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:1100 +0x525
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc000014b60, {0x1424af5, 0x5}, {0x153fdc0?, 0xc00040db30?}, {0x14ba600?, 0xc00015ddb0?, 0x0?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:488 +0x2e5
github.com/mitchellh/mapstructure.(*Decoder).decodeStructFromMap(0xc000014b60, {0x0, 0x0}, {0x1583580?, 0xc00013d980?, 0x5?}, {0x1676940?, 0xc00015dc00?, 0x15?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:1411 +0x1bd0
github.com/mitchellh/mapstructure.(*Decoder).decodeStruct(0x1537660?, {0x0, 0x0}, {0x1583580?, 0xc00013d980?}, {0x1676940?, 0xc00015dc00?, 0x2?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:1235 +0x5b4
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc000014b60, {0x0, 0x0}, {0x1583580?, 0xc00013d980?}, {0x1676940?, 0xc00015dc00?, 0x1583580?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:482 +0x309
github.com/mitchellh/mapstructure.(*Decoder).decodePtr(0xc000014b60, {0x0, 0x0}, {0x1583580, 0xc00013d980}, {0x1524de0?, 0xc000014b78?, 0x2?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:1052 +0x436
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc000014b60, {0x0, 0x0}, {0x1583580?, 0xc00013d980?}, {0x1524de0?, 0xc000014b78?, 0xc0006b7660?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:486 +0x2c9
github.com/mitchellh/mapstructure.(*Decoder).decodePtr(0xc000014b60, {0x0, 0x0}, {0x1583580, 0xc00013d980}, {0xc000328f40?, 0xc000014b78?, 0x8?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:1058 +0x4db
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc000014b60, {0x0, 0x0}, {0x1583580?, 0xc00013d980?}, {0xc000328f40?, 0xc000014b78?, 0x1522220?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:486 +0x2c9
github.com/mitchellh/mapstructure.(*Decoder).decodeBasic(0x1537660?, {0x0, 0x0}, {0x1583580?, 0xc00013d980}, {0x1522220?, 0xc000117b80?, 0x7ff6c2601cc8?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:532 +0x665
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc000014b60, {0x0, 0x0}, {0x1583580?, 0xc00013d980?}, {0x1522220?, 0xc000117b80?, 0xc0003b07c0?})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:472 +0x2a5
github.com/mitchellh/mapstructure.(*Decoder).Decode(0xc000014b60, {0x1583580, 0xc00013d980})
	/go/pkg/mod/github.com/mitchellh/mapstructure@v1.5.0/mapstructure.go:417 +0xd8
akvorado/cmd.ConfigRelatedOptions.Parse({{0x7ffd6b169f6a?, 0xc0006b7b88?}, 0xb8?, 0xc000117b70?}, {0x1f240c0, 0xc000014018}, {0x170df66, 0xc}, {0x1524de0, 0xc00015dc00})
	/app/cmd/config.go:90 +0x985
akvorado/cmd.glob..func5(0x2893ea0?, {0xc000117b40, 0x1, 0x1?})
	/app/cmd/orchestrator.go:83 +0x15e
github.com/spf13/cobra.(*Command).execute(0x2893ea0, {0xc000117b20, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x28934a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/app/main.go:15 +0x25

```
</details>

`akvorado/cmd.ConfigRelatedOptions.Parse` - this line in logs makes me think there's a problem with my `akvorado.yml` file, but I'm pretty sure I've run the same version of this file before without any issue with akvorado version 1.5.5 / 1.5.6

Earlier during tests in the orchestrator logs I saw exactly what the problem was, but in this case it is difficult for me to read the logs, it is unclear which block is causing the problem. I have tried different options but unfortunately without success

<details>
  <summary>akvorado.yaml</summary>
  

```
---
    kafka:
      topic: flows
      version: 2.8.1
      brokers:
        - kafka:9092
      topic-configuration:
        num-partitions: 8
        replication-factor: 1
        config-entries:
          segment.bytes: 1073741824
          retention.ms: 86400000
          cleanup.policy: delete
          compression.type: producer
    
    clickhouse:
      orchestrator-url: http://akvorado-orchestrator:8080
      kafka:
        consumers: 4
      servers:
        - clickhouse:9000
      asns:
        16509: AMAZON
        1299: Arelion-Telia
        174: COGENT
      networks:
        52.94.248.96/28:
          name: AWS us-west-2
          role: AWS
          site: EC2
          region: us-west-2
#### Bunch of networks ###
        99.77.186.0/24:
          name: AWS us-west-2
          role: AWS
          site: EC2
          region: us-west-2
    
    inlet:
      kafka:
        compression-codec: zstd
      geoip:
        optional: true
        asn-database: ./volumes/akvorado-geoip/GeoLite2-ASN.mmdb
        geo-database: ./volumes/akvorado-geoip/GeoLite2-Country.mmdb
      snmp:
        workers: 20
        communities: SomeSecret
      flow:
        inputs:
          - type: udp
            decoder: sflow
            listen: 0.0.0.0:6343
            workers: 20
            receive-buffer: 10485760
    
      core:
        workers: 6
        exporter-classifiers:
          - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
          - ClassifyRole("ALL")
        interface-classifiers:
          - |
            ClassifyConnectivityRegex(Interface.Description, "(^ISP1|ISP2)", "$1") &&
            ClassifyProviderRegex(Interface.Description, "(^ISP1|ISP2)", "$1") &&
            ClassifyExternal()
          - ClassifyInternal()
        default-sampling-rate: 1000

    console:
      homepage-top-widgets: [src-port, dst-port, protocol, exporter]
      default-visualize-options:
        start: 3 hours ago
        end: now
        filter: InIfBoundary = internal
        dimensions: [SrcNetSite, SrcNetRole, DstNetSite, DstNetRole]
      auth:
        headers:
          login: Remote-User
          name: Remote-Name
          email: Remote-Email
          logout-url: X-Logout-URL
        default-user:
          login: default
          name: Default User
```
</details>

Maybe you can help or advise me on the next steps. Thank you in advance!

_Originally posted by @knpshkn in https://github.com/vincentbernat/akvorado/discussions/114_
